#############################################################################
# Makefile for building: ReuseVector
# Generated by qmake (3.0) (Qt 5.3.1)
# Project:  ReuseVector.pro
# Template: subdirs
# Command: C:/Qt/5.3/mingw482_32/bin/qmake.exe -spec win32-g++ -o Makefile ReuseVector.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = C:/Qt/5.3/mingw482_32/bin/qmake.exe
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = cp -f
INSTALL_PROGRAM = cp -f
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		sub-ide-Library \
		sub-ide-Tests


sub-ide-Library-qmake_all:  FORCE
	@test -d ide/Library/ || mkdir -p ide/Library/
	cd ide/Library/ && $(QMAKE) C:/Users/Dan/Dropbox/Dev/DanWatkins/ReuseVector/ide/Library/Library.pro -spec win32-g++ -o Makefile
	cd ide/Library/ && $(MAKE) -f Makefile qmake_all
sub-ide-Library: FORCE
	@test -d ide/Library/ || mkdir -p ide/Library/
	cd ide/Library/ && ( test -e Makefile || $(QMAKE) C:/Users/Dan/Dropbox/Dev/DanWatkins/ReuseVector/ide/Library/Library.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile
sub-ide-Library-make_first-ordered: FORCE
	@test -d ide/Library/ || mkdir -p ide/Library/
	cd ide/Library/ && ( test -e Makefile || $(QMAKE) C:/Users/Dan/Dropbox/Dev/DanWatkins/ReuseVector/ide/Library/Library.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile 
sub-ide-Library-make_first: FORCE
	@test -d ide/Library/ || mkdir -p ide/Library/
	cd ide/Library/ && ( test -e Makefile || $(QMAKE) C:/Users/Dan/Dropbox/Dev/DanWatkins/ReuseVector/ide/Library/Library.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile 
sub-ide-Library-all-ordered: FORCE
	@test -d ide/Library/ || mkdir -p ide/Library/
	cd ide/Library/ && ( test -e Makefile || $(QMAKE) C:/Users/Dan/Dropbox/Dev/DanWatkins/ReuseVector/ide/Library/Library.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile all
sub-ide-Library-all: FORCE
	@test -d ide/Library/ || mkdir -p ide/Library/
	cd ide/Library/ && ( test -e Makefile || $(QMAKE) C:/Users/Dan/Dropbox/Dev/DanWatkins/ReuseVector/ide/Library/Library.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile all
sub-ide-Library-clean-ordered: FORCE
	@test -d ide/Library/ || mkdir -p ide/Library/
	cd ide/Library/ && ( test -e Makefile || $(QMAKE) C:/Users/Dan/Dropbox/Dev/DanWatkins/ReuseVector/ide/Library/Library.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile clean
sub-ide-Library-clean: FORCE
	@test -d ide/Library/ || mkdir -p ide/Library/
	cd ide/Library/ && ( test -e Makefile || $(QMAKE) C:/Users/Dan/Dropbox/Dev/DanWatkins/ReuseVector/ide/Library/Library.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile clean
sub-ide-Library-distclean-ordered: FORCE
	@test -d ide/Library/ || mkdir -p ide/Library/
	cd ide/Library/ && ( test -e Makefile || $(QMAKE) C:/Users/Dan/Dropbox/Dev/DanWatkins/ReuseVector/ide/Library/Library.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile distclean
sub-ide-Library-distclean: FORCE
	@test -d ide/Library/ || mkdir -p ide/Library/
	cd ide/Library/ && ( test -e Makefile || $(QMAKE) C:/Users/Dan/Dropbox/Dev/DanWatkins/ReuseVector/ide/Library/Library.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile distclean
sub-ide-Library-install_subtargets-ordered: FORCE
	@test -d ide/Library/ || mkdir -p ide/Library/
	cd ide/Library/ && ( test -e Makefile || $(QMAKE) C:/Users/Dan/Dropbox/Dev/DanWatkins/ReuseVector/ide/Library/Library.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile install
sub-ide-Library-install_subtargets: FORCE
	@test -d ide/Library/ || mkdir -p ide/Library/
	cd ide/Library/ && ( test -e Makefile || $(QMAKE) C:/Users/Dan/Dropbox/Dev/DanWatkins/ReuseVector/ide/Library/Library.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile install
sub-ide-Library-uninstall_subtargets-ordered: FORCE
	@test -d ide/Library/ || mkdir -p ide/Library/
	cd ide/Library/ && ( test -e Makefile || $(QMAKE) C:/Users/Dan/Dropbox/Dev/DanWatkins/ReuseVector/ide/Library/Library.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-ide-Library-uninstall_subtargets: FORCE
	@test -d ide/Library/ || mkdir -p ide/Library/
	cd ide/Library/ && ( test -e Makefile || $(QMAKE) C:/Users/Dan/Dropbox/Dev/DanWatkins/ReuseVector/ide/Library/Library.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-ide-Tests-qmake_all: sub-ide-Library-qmake_all FORCE
	@test -d ide/Tests/ || mkdir -p ide/Tests/
	cd ide/Tests/ && $(QMAKE) C:/Users/Dan/Dropbox/Dev/DanWatkins/ReuseVector/ide/Tests/Tests.pro -spec win32-g++ -o Makefile
	cd ide/Tests/ && $(MAKE) -f Makefile qmake_all
sub-ide-Tests: FORCE
	@test -d ide/Tests/ || mkdir -p ide/Tests/
	cd ide/Tests/ && ( test -e Makefile || $(QMAKE) C:/Users/Dan/Dropbox/Dev/DanWatkins/ReuseVector/ide/Tests/Tests.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile
sub-ide-Tests-make_first-ordered: sub-ide-Library-make_first-ordered  FORCE
	@test -d ide/Tests/ || mkdir -p ide/Tests/
	cd ide/Tests/ && ( test -e Makefile || $(QMAKE) C:/Users/Dan/Dropbox/Dev/DanWatkins/ReuseVector/ide/Tests/Tests.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile 
sub-ide-Tests-make_first: FORCE
	@test -d ide/Tests/ || mkdir -p ide/Tests/
	cd ide/Tests/ && ( test -e Makefile || $(QMAKE) C:/Users/Dan/Dropbox/Dev/DanWatkins/ReuseVector/ide/Tests/Tests.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile 
sub-ide-Tests-all-ordered: sub-ide-Library-all-ordered  FORCE
	@test -d ide/Tests/ || mkdir -p ide/Tests/
	cd ide/Tests/ && ( test -e Makefile || $(QMAKE) C:/Users/Dan/Dropbox/Dev/DanWatkins/ReuseVector/ide/Tests/Tests.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile all
sub-ide-Tests-all: FORCE
	@test -d ide/Tests/ || mkdir -p ide/Tests/
	cd ide/Tests/ && ( test -e Makefile || $(QMAKE) C:/Users/Dan/Dropbox/Dev/DanWatkins/ReuseVector/ide/Tests/Tests.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile all
sub-ide-Tests-clean-ordered: sub-ide-Library-clean-ordered  FORCE
	@test -d ide/Tests/ || mkdir -p ide/Tests/
	cd ide/Tests/ && ( test -e Makefile || $(QMAKE) C:/Users/Dan/Dropbox/Dev/DanWatkins/ReuseVector/ide/Tests/Tests.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile clean
sub-ide-Tests-clean: FORCE
	@test -d ide/Tests/ || mkdir -p ide/Tests/
	cd ide/Tests/ && ( test -e Makefile || $(QMAKE) C:/Users/Dan/Dropbox/Dev/DanWatkins/ReuseVector/ide/Tests/Tests.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile clean
sub-ide-Tests-distclean-ordered: sub-ide-Library-distclean-ordered  FORCE
	@test -d ide/Tests/ || mkdir -p ide/Tests/
	cd ide/Tests/ && ( test -e Makefile || $(QMAKE) C:/Users/Dan/Dropbox/Dev/DanWatkins/ReuseVector/ide/Tests/Tests.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile distclean
sub-ide-Tests-distclean: FORCE
	@test -d ide/Tests/ || mkdir -p ide/Tests/
	cd ide/Tests/ && ( test -e Makefile || $(QMAKE) C:/Users/Dan/Dropbox/Dev/DanWatkins/ReuseVector/ide/Tests/Tests.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile distclean
sub-ide-Tests-install_subtargets-ordered: sub-ide-Library-install_subtargets-ordered  FORCE
	@test -d ide/Tests/ || mkdir -p ide/Tests/
	cd ide/Tests/ && ( test -e Makefile || $(QMAKE) C:/Users/Dan/Dropbox/Dev/DanWatkins/ReuseVector/ide/Tests/Tests.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile install
sub-ide-Tests-install_subtargets: FORCE
	@test -d ide/Tests/ || mkdir -p ide/Tests/
	cd ide/Tests/ && ( test -e Makefile || $(QMAKE) C:/Users/Dan/Dropbox/Dev/DanWatkins/ReuseVector/ide/Tests/Tests.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile install
sub-ide-Tests-uninstall_subtargets-ordered: sub-ide-Library-uninstall_subtargets-ordered  FORCE
	@test -d ide/Tests/ || mkdir -p ide/Tests/
	cd ide/Tests/ && ( test -e Makefile || $(QMAKE) C:/Users/Dan/Dropbox/Dev/DanWatkins/ReuseVector/ide/Tests/Tests.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-ide-Tests-uninstall_subtargets: FORCE
	@test -d ide/Tests/ || mkdir -p ide/Tests/
	cd ide/Tests/ && ( test -e Makefile || $(QMAKE) C:/Users/Dan/Dropbox/Dev/DanWatkins/ReuseVector/ide/Tests/Tests.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: ReuseVector.pro C:/Qt/5.3/mingw482_32/mkspecs/win32-g++/qmake.conf C:/Qt/5.3/mingw482_32/mkspecs/features/spec_pre.prf \
		C:/Qt/5.3/mingw482_32/mkspecs/qdevice.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/features/device_config.prf \
		C:/Qt/5.3/mingw482_32/mkspecs/common/shell-unix.conf \
		C:/Qt/5.3/mingw482_32/mkspecs/qconfig.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_axbase.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_axbase_private.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_axcontainer.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_axcontainer_private.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_axserver.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_axserver_private.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_bluetooth.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_bluetooth_private.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_bootstrap_private.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_clucene_private.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_concurrent.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_concurrent_private.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_core.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_core_private.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_declarative.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_declarative_private.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_designer.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_designer_private.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_designercomponents_private.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_enginio.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_enginio_private.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_gui.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_gui_private.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_help.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_help_private.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_multimedia.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_multimedia_private.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_multimediawidgets.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_network.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_network_private.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_nfc.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_nfc_private.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_opengl.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_opengl_private.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_openglextensions.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_openglextensions_private.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_platformsupport_private.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_positioning.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_positioning_private.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_printsupport.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_printsupport_private.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_qml.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_qml_private.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_qmltest.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_qmltest_private.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_quick.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_quick_private.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_quickparticles_private.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_quickwidgets.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_script.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_script_private.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_scripttools.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_scripttools_private.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_sensors.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_sensors_private.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_serialport.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_serialport_private.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_sql.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_sql_private.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_svg.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_svg_private.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_testlib.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_testlib_private.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_uitools.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_uitools_private.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_webkit.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_webkit_private.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_webkitwidgets.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_websockets.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_websockets_private.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_widgets.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_widgets_private.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_winextras.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_winextras_private.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_xml.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_xml_private.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_xmlpatterns.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		C:/Qt/5.3/mingw482_32/mkspecs/features/qt_functions.prf \
		C:/Qt/5.3/mingw482_32/mkspecs/features/qt_config.prf \
		C:/Qt/5.3/mingw482_32/mkspecs/features/win32/qt_config.prf \
		C:/Qt/5.3/mingw482_32/mkspecs/win32-g++/qmake.conf \
		C:/Qt/5.3/mingw482_32/mkspecs/features/spec_post.prf \
		C:/Qt/5.3/mingw482_32/mkspecs/features/exclusive_builds.prf \
		C:/Qt/5.3/mingw482_32/mkspecs/features/default_pre.prf \
		C:/Qt/5.3/mingw482_32/mkspecs/features/win32/default_pre.prf \
		C:/Qt/5.3/mingw482_32/mkspecs/features/resolve_config.prf \
		C:/Qt/5.3/mingw482_32/mkspecs/features/exclusive_builds_post.prf \
		C:/Qt/5.3/mingw482_32/mkspecs/features/default_post.prf \
		C:/Qt/5.3/mingw482_32/mkspecs/features/win32/rtti.prf \
		C:/Qt/5.3/mingw482_32/mkspecs/features/precompile_header.prf \
		C:/Qt/5.3/mingw482_32/mkspecs/features/warn_on.prf \
		C:/Qt/5.3/mingw482_32/mkspecs/features/win32/windows.prf \
		C:/Qt/5.3/mingw482_32/mkspecs/features/testcase_targets.prf \
		C:/Qt/5.3/mingw482_32/mkspecs/features/exceptions.prf \
		C:/Qt/5.3/mingw482_32/mkspecs/features/yacc.prf \
		C:/Qt/5.3/mingw482_32/mkspecs/features/lex.prf \
		ReuseVector.pro
	$(QMAKE) -spec win32-g++ -o Makefile ReuseVector.pro
C:/Qt/5.3/mingw482_32/mkspecs/features/spec_pre.prf:
C:/Qt/5.3/mingw482_32/mkspecs/qdevice.pri:
C:/Qt/5.3/mingw482_32/mkspecs/features/device_config.prf:
C:/Qt/5.3/mingw482_32/mkspecs/common/shell-unix.conf:
C:/Qt/5.3/mingw482_32/mkspecs/qconfig.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_axbase.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_axbase_private.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_axcontainer.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_axcontainer_private.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_axserver.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_axserver_private.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_bluetooth.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_bluetooth_private.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_bootstrap_private.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_clucene_private.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_concurrent.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_concurrent_private.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_core.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_core_private.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_declarative.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_declarative_private.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_designer.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_designer_private.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_designercomponents_private.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_enginio.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_enginio_private.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_gui.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_gui_private.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_help.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_help_private.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_multimedia.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_multimedia_private.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_multimediawidgets.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_network.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_network_private.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_nfc.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_nfc_private.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_opengl.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_opengl_private.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_openglextensions.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_openglextensions_private.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_platformsupport_private.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_positioning.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_positioning_private.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_printsupport.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_printsupport_private.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_qml.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_qml_private.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_qmldevtools_private.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_qmltest.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_qmltest_private.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_quick.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_quick_private.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_quickparticles_private.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_quickwidgets.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_quickwidgets_private.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_script.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_script_private.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_scripttools.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_scripttools_private.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_sensors.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_sensors_private.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_serialport.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_serialport_private.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_sql.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_sql_private.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_svg.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_svg_private.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_testlib.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_testlib_private.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_uitools.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_uitools_private.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_webkit.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_webkit_private.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_webkitwidgets.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_websockets.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_websockets_private.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_widgets.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_widgets_private.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_winextras.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_winextras_private.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_xml.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_xml_private.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_xmlpatterns.pri:
C:/Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
C:/Qt/5.3/mingw482_32/mkspecs/features/qt_functions.prf:
C:/Qt/5.3/mingw482_32/mkspecs/features/qt_config.prf:
C:/Qt/5.3/mingw482_32/mkspecs/features/win32/qt_config.prf:
C:/Qt/5.3/mingw482_32/mkspecs/win32-g++/qmake.conf:
C:/Qt/5.3/mingw482_32/mkspecs/features/spec_post.prf:
C:/Qt/5.3/mingw482_32/mkspecs/features/exclusive_builds.prf:
C:/Qt/5.3/mingw482_32/mkspecs/features/default_pre.prf:
C:/Qt/5.3/mingw482_32/mkspecs/features/win32/default_pre.prf:
C:/Qt/5.3/mingw482_32/mkspecs/features/resolve_config.prf:
C:/Qt/5.3/mingw482_32/mkspecs/features/exclusive_builds_post.prf:
C:/Qt/5.3/mingw482_32/mkspecs/features/default_post.prf:
C:/Qt/5.3/mingw482_32/mkspecs/features/win32/rtti.prf:
C:/Qt/5.3/mingw482_32/mkspecs/features/precompile_header.prf:
C:/Qt/5.3/mingw482_32/mkspecs/features/warn_on.prf:
C:/Qt/5.3/mingw482_32/mkspecs/features/win32/windows.prf:
C:/Qt/5.3/mingw482_32/mkspecs/features/testcase_targets.prf:
C:/Qt/5.3/mingw482_32/mkspecs/features/exceptions.prf:
C:/Qt/5.3/mingw482_32/mkspecs/features/yacc.prf:
C:/Qt/5.3/mingw482_32/mkspecs/features/lex.prf:
ReuseVector.pro:
qmake: FORCE
	@$(QMAKE) -spec win32-g++ -o Makefile ReuseVector.pro

qmake_all: sub-ide-Library-qmake_all sub-ide-Tests-qmake_all FORCE

make_first: sub-ide-Library-make_first-ordered sub-ide-Tests-make_first-ordered FORCE
all: sub-ide-Library-all-ordered sub-ide-Tests-all-ordered FORCE
clean: sub-ide-Library-clean-ordered sub-ide-Tests-clean-ordered FORCE
distclean: sub-ide-Library-distclean-ordered sub-ide-Tests-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-ide-Library-install_subtargets-ordered sub-ide-Tests-install_subtargets-ordered FORCE
uninstall_subtargets: sub-ide-Library-uninstall_subtargets-ordered sub-ide-Tests-uninstall_subtargets-ordered FORCE

sub-ide-Library-debug_ordered:
	@test -d ide/Library/ || mkdir -p ide/Library/
	cd ide/Library/ && ( test -e Makefile || $(QMAKE) C:/Users/Dan/Dropbox/Dev/DanWatkins/ReuseVector/ide/Library/Library.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile debug
sub-ide-Tests-debug_ordered: sub-ide-Library-debug_ordered 
	@test -d ide/Tests/ || mkdir -p ide/Tests/
	cd ide/Tests/ && ( test -e Makefile || $(QMAKE) C:/Users/Dan/Dropbox/Dev/DanWatkins/ReuseVector/ide/Tests/Tests.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile debug
debug: sub-ide-Library-debug_ordered sub-ide-Tests-debug_ordered

sub-ide-Library-release_ordered:
	@test -d ide/Library/ || mkdir -p ide/Library/
	cd ide/Library/ && ( test -e Makefile || $(QMAKE) C:/Users/Dan/Dropbox/Dev/DanWatkins/ReuseVector/ide/Library/Library.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile release
sub-ide-Tests-release_ordered: sub-ide-Library-release_ordered 
	@test -d ide/Tests/ || mkdir -p ide/Tests/
	cd ide/Tests/ && ( test -e Makefile || $(QMAKE) C:/Users/Dan/Dropbox/Dev/DanWatkins/ReuseVector/ide/Tests/Tests.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile release
release: sub-ide-Library-release_ordered sub-ide-Tests-release_ordered

sub-ide-Library-check_ordered:
	@test -d ide/Library/ || mkdir -p ide/Library/
	cd ide/Library/ && ( test -e Makefile || $(QMAKE) C:/Users/Dan/Dropbox/Dev/DanWatkins/ReuseVector/ide/Library/Library.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile check
sub-ide-Tests-check_ordered: sub-ide-Library-check_ordered 
	@test -d ide/Tests/ || mkdir -p ide/Tests/
	cd ide/Tests/ && ( test -e Makefile || $(QMAKE) C:/Users/Dan/Dropbox/Dev/DanWatkins/ReuseVector/ide/Tests/Tests.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile check
check: sub-ide-Library-check_ordered sub-ide-Tests-check_ordered
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

